INSERT INTO users(name, point, created_at, updated_at) VALUES ('유저1', 0, now(), now())

INSERT INTO performance(title, content, created_at, updated_at) VALUES ('공연1', '내용1', now(), now())
INSERT INTO performance(title, content, created_at, updated_at) VALUES ('공연2', '내용2', now(), now())
INSERT INTO performance(title, content, created_at, updated_at) VALUES ('공연3', '내용3', now(), now())
INSERT INTO performance(title, content, created_at, updated_at) VALUES ('공연4', '내용4', now(), now())
INSERT INTO performance(title, content, created_at, updated_at) VALUES ('공연5', '내용5', now(), now())

INSERT INTO performance_schedule(performance_id, start_at, end_at, reservation_at, created_at, updated_at) VALUES(1, now(), now(), now(), now(), now())
INSERT INTO performance_schedule(performance_id, start_at, end_at, reservation_at, created_at, updated_at) VALUES(1, now(), now(), now(), now(), now())
INSERT INTO performance_schedule(performance_id, start_at, end_at, reservation_at, created_at, updated_at) VALUES(1, now(), now(), now(), now(), now())

INSERT INTO seat(performance_schedule_id, seat_no, price, status, created_at, updated_at) VALUES(1, 1, 10000, 'RESERVED', now(), now())
INSERT INTO seat(performance_schedule_id, seat_no, price, status, created_at, updated_at) VALUES(1, 2, 10000, 'OPEN', now(), now())
INSERT INTO seat(performance_schedule_id, seat_no, price, status, created_at, updated_at) VALUES(1, 3, 10000, 'RESERVED', now(), now())
INSERT INTO seat(performance_schedule_id, seat_no, price, status, created_at, updated_at) VALUES(1, 4, 10000, 'RESERVED', now(), now())
INSERT INTO seat(performance_schedule_id, seat_no, price, status, created_at, updated_at) VALUES(1, 5, 10000, 'OPEN', now(), now())
INSERT INTO seat(performance_schedule_id, seat_no, price, status, created_at, updated_at) VALUES(1, 6, 20000, 'RESERVED', now(), now())
INSERT INTO seat(performance_schedule_id, seat_no, price, status, created_at, updated_at) VALUES(1, 7, 20000, 'OPEN', now(), now())
INSERT INTO seat(performance_schedule_id, seat_no, price, status, created_at, updated_at) VALUES(1, 8, 20000, 'RESERVED', now(), now())
INSERT INTO seat(performance_schedule_id, seat_no, price, status, created_at, updated_at) VALUES(1, 9, 20000, 'RESERVED', now(), now())
INSERT INTO seat(performance_schedule_id, seat_no, price, status, created_at, updated_at) VALUES(1, 10, 20000, 'OPEN', now(), now())